# Generated by Django 5.1 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='लेखक का नाम (Author Name)')),
                ('role', models.CharField(max_length=120, verbose_name='पद / विशेषज्ञता (Role)')),
                ('avatar', models.URLField(max_length=500, verbose_name='प्रोफाइल फोटो URL (Avatar URL)')),
                ('bio', models.TextField(verbose_name='संक्षिप्त परिचय (Bio)')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='ट्विटर / X हैंडल')),
                ('articles_count', models.PositiveIntegerField(default=0, verbose_name='प्रकाशित लेख संख्या')),
            ],
            options={
                'verbose_name': 'लेखक / संपादक (Author)',
                'verbose_name_plural': 'लेखक व संपादक टीम (Authors & Editorial Team)',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='श्रेणी का नाम (Category Name)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL स्लग (Slug)')),
                ('description', models.TextField(blank=True, verbose_name='श्रेणी विवरण (Description)')),
                ('icon', models.CharField(default='terminal', max_length=50, verbose_name='आइकन नाम (Material Icon)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Google SEO Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Google SEO Meta Description')),
            ],
            options={
                'verbose_name': 'श्रेणी (Category)',
                'verbose_name_plural': 'श्रेणियां (Categories)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ईमेल पता')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='सदस्यता तिथि')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
            ],
            options={
                'verbose_name': 'न्यूज़लेटर सब्सक्राइबर',
                'verbose_name_plural': 'न्यूज़लेटर सब्सक्राइबर्स',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='पेज का नाम (Page Title)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL स्लग')),
                ('content', models.TextField(verbose_name='पेज की सामग्री (HTML/Text)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Google SEO Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Google SEO Meta Description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='अंतिम अपडेट')),
            ],
            options={
                'verbose_name': 'स्टैटिक पेज (Static Page)',
                'verbose_name_plural': 'स्टैटिक पेजेस (Static Pages)',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='टैग नाम (Tag Name)')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='टैग स्लग (Slug)')),
            ],
            options={
                'verbose_name': 'टैग (Tag)',
                'verbose_name_plural': 'टैग्स (Tags)',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='आर्टिकल का मुख्य शीर्षक (Title)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL स्लग (Slug)')),
                ('excerpt', models.TextField(verbose_name='संक्षिप्त सारांश (Excerpt/Summary)')),
                ('content', models.TextField(verbose_name='विस्तृत लेख सामग्री (Article Content - Markdown or HTML)')),
                ('cover_image', models.URLField(max_length=600, verbose_name='कवर फोटो URL (Cover Image URL)')),
                ('image_alt', models.CharField(blank=True, default='TechVani Article Cover', max_length=255, verbose_name='इमेज Alt टेक्स्ट (SEO के लिए)')),
                ('sub_category', models.CharField(blank=True, max_length=50, verbose_name='सब-कैटेगरी / टैब (उदा: Python, Web Dev, टूलकिट)')),
                ('meta_title', models.CharField(blank=True, help_text='गूगल सर्च में दिखने वाला शीर्षक। यदि खाली छोड़ेंगे तो मुख्य Title उपयोग होगा।', max_length=255, verbose_name='Google SEO Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='गूगल सर्च स्निपेट (अनुशंसित: 120-160 अक्षर)। यदि खाली छोड़ेंगे तो Excerpt उपयोग होगा।', verbose_name='Google SEO Meta Description')),
                ('canonical_url', models.URLField(blank=True, help_text='कैनोनिकल लिंक (सर्च इंजन में डुप्लिकेट कंटेंट से बचाव के लिए)।', verbose_name='Canonical URL')),
                ('keywords', models.CharField(blank=True, help_text='कॉमा से अलग किए गए कीवर्ड्स (उदा: विंडोज 11, कीबोर्ड शॉर्टकट्स, एक्सेल)', max_length=500, verbose_name='Meta Keywords')),
                ('og_image', models.URLField(blank=True, help_text='फेसबुक / ट्विटर पर शेयर करते समय दिखने वाली इमेज (यदि खाली छोड़ेंगे तो Cover Image उपयोग होगी)।', max_length=600, verbose_name='सोशल शेयर इमेज (OpenGraph Image)')),
                ('schema_type', models.CharField(choices=[('TechArticle', 'Tech Article (तकनीकी लेख)'), ('NewsArticle', 'News Article (समाचार)'), ('Product', 'Product Review (उत्पाद / गैजेट समीक्षा)'), ('HowTo', 'How-To Guide (कीबोर्ड शॉर्टकट / ट्यूटोरियल)')], default='TechArticle', help_text='गूगल रिच सर्च स्निपेट्स के लिए संरचित डेटा प्रकार।', max_length=50, verbose_name='Google Schema.org प्रकार (Schema Type)')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='समीक्षा रेटिंग / 10 (Review Rating)')),
                ('product_price', models.CharField(blank=True, max_length=100, verbose_name='अनुमानित कीमत (उदा: ₹3,499)')),
                ('video_duration', models.CharField(blank=True, max_length=50, verbose_name='वीडियो अवधि (उदा: 58 मिनट)')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='क्या प्रकाशित है? (Published)')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='मुख्य फीचर लेख (Featured Article)')),
                ('is_editorial_choice', models.BooleanField(db_index=True, default=False, verbose_name='संपादकीय पसंद (Editorial Choice)')),
                ('is_trending', models.BooleanField(db_index=True, default=False, verbose_name='ट्रेंडिंग में दिखाएं (Trending)')),
                ('featured_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='हीरो ग्रिड क्रम (0 = सामान्य, 1 = बड़ा हीरो, 2, 3 = साइड कार्ड्स)')),
                ('reading_time_minutes', models.PositiveIntegerField(default=5, verbose_name='पढ़ने का समय (मिनट में)')),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='व्यूज संख्या (Views Count)')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='टिप्पणियां संख्या (Comments Count)')),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='प्रकाशन तिथि (Published Date)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='अंतिम संशोधन तिथि (Updated Date)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.author', verbose_name='लेखक (Author)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.category', verbose_name='मुख्य श्रेणी (Category)')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='टैग्स (Tags)')),
            ],
            options={
                'verbose_name': 'ब्लॉग पोस्ट / आर्टिकल (Article)',
                'verbose_name_plural': 'ब्लॉग पोस्ट्स (Articles)',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='नाम (Name)')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='ईमेल (Email)')),
                ('comment', models.TextField(verbose_name='टिप्पणी (Comment Text)')),
                ('is_approved', models.BooleanField(default=True, verbose_name='स्वीकृत (Approved)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='दिनांक (Date)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='आर्टिकल')),
            ],
            options={
                'verbose_name': 'टिप्पणी (Comment)',
                'verbose_name_plural': 'टिप्पणियां (Comments)',
                'ordering': ['-created_at'],
            },
        ),
    ]
