# Generated by Django 5.1.2 on 2026-10-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'टिप्पणी (Comment)', 'verbose_name_plural': 'पाठकों की टिप्पणियां (Comments)'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name': 'न्यूज़लेटर सब्सक्राइबर', 'verbose_name_plural': 'न्यूज़लेटर ग्राहक सूची (Newsletter Subscribers)'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'स्टैटिक पेज (Static Policy/About Page)', 'verbose_name_plural': 'पेज प्रबंधन (Pages: About, Privacy, Contact)'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='संबंधित आर्टिकल'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ईमेल पता'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=120, verbose_name='पाठक का नाम'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='दिनांक'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='क्या स्वीकृत है?'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='एक्टिव सदस्य'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='सब्सक्रिप्शन तिथि'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(verbose_name='पेज सामग्री (Content HTML/Text)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Google Meta Description'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Meta Title'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL स्लग (उदा: about, privacy-policy)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='पेज का शीर्षक (Title)'),
        ),
    ]
